### PR TITLE
support +&- evidence markers

### LINKED ISSUE #32: Support both positive and negative marker gene evidence
This would split the evidence marker field into two fields.

Motivating use case - evidence for annotation in Siletti 2023 includes both positive and negative markers, e.g. see 
https://github.com/linnarsson-lab/auto-annotation-ah/blob/main/Human_adult/Class/ASTRO.md?plain=1

### PR DESCRIPTION
**Pull request by dosumis**
Fixes #32

@mfutey @evanbiederstedt - would be good to add this as we have examples to support for Siletti.  Can hold off until you agree on matching update to CAP AnnData spec.

### CODE REVIEW

**Review by evanbiederstedt — COMMENTED** [review]
@dosumis 
This possibly isn't helpful, but I'm still on the fence about this. 

Only certain biological communities appear to count negative markers. I think it's coming up for Brain, and for Blood. 

Making this a standard becomes therefore tricky. It feels like an optional field for the current version, no?

**Update:** 
How about this as a solution:
- Marker genes are "positive marker genes". That's a required field. It's applicable to all. We simply clarify this in the description.
- The field "negative marker genes" would therefore become optional.

**Comment by dosumis** [comment]
Neither field is mandatory.  I think I'd rather be explicit in naming and use 'positive marker genes' - although this will cause some backwards compatibility issues.

**Comment by evanbiederstedt** [comment]
"marker genes" is mandatory for CAP

Therefore, I'd prefer that "positive and negative" are only used explicitly if it's relevant for the project. In this case, the positive markers could be listed in "marker genes"

**Comment by dosumis** [comment]
Fixed.  Please check and approve if now OK. Ta

**Review by evanbiederstedt — APPROVED** [review]
LGTM

BTW, I'd be happy supporting a (repeat) "positive marker" field if being explicit is helpful

**Pull request merged**
