### PR TITLE
Update CAP_extension.json

### LINKED ISSUE #59: Adding category fields to the CAP extension
These fields were in earlier versions of the schema but got lost in moving repos etc.
Up to date reference for these fields:
 - https://github.com/cellannotation/cap_file_planning/blob/main/cap_anndata_schema.md#cellannotation_setname--category_fullname - and fields below this.

### PR DESCRIPTION
**Pull request by dosumis**
Fixes #59

### CODE REVIEW

**Comment by dosumis** [comment]
Needs test example.  @mfutey - do you have some examples of categories from curation (Maybe categories are something we only expect to get from CAP?)

**Comment by mfutey** [comment]
@dosumis the category is the parent value for the value in the [cellannotation_setname], here is an example from a retina dataset: 

| cluster2--cell_fullname  | cluster2--cell_ontology_term_id  | cluster2--cell_ontology_term  | cluster2--category_fullname  | cluster2--category_cell_ontology_exists  | cluster2--category_cell_ontology_term_id  | cluster2--category_cell_ontology_term  |
|:----------|:----------|:----------|:----------|:----------|:----------|:----------|
| flat midget bipolar    | CL:4033033    | flat midget bipolar cell    | cone OFF    | True    | CL:0000750    | OFF-bipolar cell    |

**Comment by dosumis** [comment]
Hi @mfutey - thanks for the example.  I'll use it for a test.  Do you have a whole sheet or anndata file that this comes from?

**Comment by mfutey** [comment]
@dosumis Here is the sheet: https://docs.google.com/spreadsheets/d/1C3U-s-tiYzjruY1BGt1OksDia9wvfTKQS1TCQDgrAY4/edit#gid=0

Do you have access to the Bayes server? If so, here is the dataset path: /home/cap/retinaBioNetwork/formattedDatasets/snRNA_BC_normalized_formatted.h5ad

If not, please find the dataset in the following google drive folder and let me know once you have downloaded it so I can delete it: https://drive.google.com/drive/u/0/folders/1Tt_3p5ln8RlNV7KTD5S853y6WMlYlYgX

**Review by evanbiederstedt — APPROVED** [review]
This works for me

**Review by mfutey — APPROVED** [review]

**Pull request merged**
